workspace:
  base: /build
  path: export-docs

pipeline:
  build: 
    image: registry.webix.io/madoka-build-env
    pull: true
    secrets: [ aws_access_key_id, aws_secret_access_key, hook_token ]
    commands:
      - ln -s /madoka ../madoka
      - ./build.sh gantt 2>&1
      - curl "http://dhtmlx.com:2280/h00ks/docs-release?token=$$HOOK_TOKEN&name=gantt"
    when:
      branch: master
